### ISSUE TITLE
Please add it to modrinth or curseforge

### ISSUE THREAD

**Issue by Mafy-17** [apace100/apoli#111]
Please add it to modrinth or curseforge

**Comment by ChrysanthCow** [comment]
I've discussed this with Apace in the past, and he said that he'd want to automate releases if he were to do this, because Calio, Apoli and Origins all being released manually is time consuming.

**Comment by Mafy-17** [comment]
fair enough but it is so annoying updating apoli in a modpack or a set of client mods
