### ISSUE TITLE
`origins:modify_crafting` not working as expected

### ISSUE THREAD

**Issue by QuantumXenon** [apace100/apoli#121]
I have a power which adds enchantments and attributes to armour pieces after they have been crafted using a custom recipe with `origins:modify_crafting`. The power works for the chestplate and leggings, but not the helmet or boots. 

The same power works for all armour pieces on the Forge version of Origins, and using the same tag with a `/give` command also works for all pieces. This leads me to believe that there might be a problem with Apoli as the enchantments are not applied with Fabric.

Here is the part power of the power that does not work for reference:
```
"type":"origins:modify_crafting",
"recipe":"origins-plus-plus:golden_helmet",
"result":{
     "item":"minecraft:golden_helmet",
     "tag":"{display:{Name:'{\"text\":\"Reinforced Golden Helmet\",\"color\":\"gold\",\"italic\":false}'},Enchantments:[{id:\"minecraft:unbreaking\",lvl:5s}],AttributeModifiers:[{AttributeName:\"generic.armor\",Name:\"generic.armor\",Amount:3,Operation:0,UUID:[I;1814394369,-248100519,-1820391739,451319416],Slot:\"head\"},{AttributeName:\"generic.armor_toughness\",Name:\"generic.armor_toughness\",Amount:2,Operation:0,UUID:[I;1963018794,-476951717,-1683060164,-713058874],Slot:\"head\"}]}"
}
```

**Comment by essickmango** [comment]
This seems to have something to do with the names of the recipes, see this minimal example datapack (derived from the aqua chidori origin mod).

What this datapack does for me:
- The `test:modify_crafting_water_breathing1` power works as expected (glass bottle & seagrass -> water breathing potion)
- The `test:modify_crafting_healing1` power doesn't work (glass bottle & kelp -> glass, original recipe)
- The `test:modify_crafting_healing2` power works (glass & kelp -> healing potion). Renaming the base recipe from `test.json` to `healing2.json` (in the power as well) breaks the power.

Interestingly in the base aqua chidori mod (https://www.curseforge.com/minecraft/mc-mods/aqua-chidori-origin-origins-addon) the water breathing potion crafting power doesn't work as well.

[minimal.zip](https://github.com/apace100/apoli/files/12438168/minimal.zip)

EDIT:
Running on minecraft 1.20.1, fabric loader 0.14.22, fabric API 7.2.1, origins 1.10, cardinal 5.2.2, Cloth 11.1.106, Mod Menu 7.2.1, i.e. newest as of today.
