### ISSUE TITLE
`apoli:holder` item action type does not function on empty stacks

### ISSUE THREAD

**Issue by ChrysanthCow** [apace100/apoli#122]
This issue happens because the interface that links an entity to ItemStacks is not being set.

This also/will also apply to any addon or future content that references this interface.

**Comment by eggohito** [comment]
I haven't taken a closer look, but at a glance, it should work fine since `EntityLinkedItemStack#getEntity` will return the vanilla holder of the item stack (set and get by `ItemStack#setHolder` and `ItemStack#getHolder` respectively) if it's not null. The `ItemStack#setHolder` is called at the end of the base tick of a living entity.

Though I do see a potential issue where the holder is not set when copying the item stack, since `apoli$holdingEntity` is not set if `ItemStack#setHolder` is called

**Comment by ChrysanthCow** [comment]
> I haven't taken a closer look, but at a glance, it should work fine since `EntityLinkedItemStack#getEntity` will return the vanilla holder of the item stack (set and get by `ItemStack#setHolder` and `ItemStack#getHolder` respectively) if it's not null. The `ItemStack#setHolder` is called at the end of the base tick of a living entity.
> 
> Though I do see a potential issue where the holder is not set when copying the item stack, since `apoli$holdingEntity` is not set if `ItemStack#setHolder` is called

The vanilla `ItemStack#getHolder` and `ItemStack#setHolder` methods are only used by Item Frames to my knowledge.

Edit: Only item frames and item entities.
Same method, just in mojmap.
![image](https://github.com/apace100/apoli/assets/81167232/13edbe1c-cd8c-4900-b6ba-cb451352c258)

**Comment by eggohito** [comment]
Apoli uses it in the [`LivingEntityMixin` class](https://github.com/apace100/apoli/blob/1.20/src/main/java/io/github/apace100/apoli/mixin/LivingEntityMixin.java#L509-L512) for setting the holder of all the item stacks in the entity's inventory (and inventories of powers that uses the `inventory` power type) at the end of the entity's base tick, though not sure why that wasn't shown in IntelliJ :thinking:

**Comment by ChrysanthCow** [comment]
The method is broken atm apparently, Apace said that he saw a problem with it when I brought it up with him.

**Comment by ChrysanthCow** [comment]
> Apoli uses it in the [`LivingEntityMixin` class](https://github.com/apace100/apoli/blob/1.20/src/main/java/io/github/apace100/apoli/mixin/LivingEntityMixin.java#L509-L512) for setting the holder of all the item stacks in the entity's inventory (and inventories of powers that uses the `inventory` power type) at the end of the entity's base tick, though not sure why that wasn't shown in IntelliJ 🤔

It's not shown in IntelliJ because of my own environment.

**Comment by ChrysanthCow** [comment]
Update: It's only broken on empty itemstacks. I've implemented a fix for this through PR #108 as it was necessary for it to function.

Apace said that this was non vital because people probably aren't using this action with an empty itemstack but I feel like it should account for it.
