### ISSUE TITLE
`apoli:modify_attribute` only functions on vanilla attributes.

### ISSUE THREAD

**Issue by ChrysanthCow** [apace100/apoli#140]
I'm reporting this as I've heard about this not working from two sources. I don't have concrete testing myself but it's seems to be the case.

**Comment by eggohito** [comment]
I can also now confirm this. Reach Entity Attributes and Additional Entity Attributes uses `EntityAttributeInstance#getValue` for getting the value of their custom attributes, whereas the `modify_attribute` power type only affects the value of the specified attribute through `LivingEntity#getAttributeValue`
