### ISSUE TITLE
[1.19.2] Failed Apoli build for Origins version 1.7.1

### ISSUE THREAD

**Issue by elytrafae** [apace100/apoli#153]
I have attempted to add Origins (and thus Apoli) as a dependency to my mod, however the Apoli build 624eb4d094 failed due to it being unable to find AdditionalEntityAttributes.

Here is the log from jitpack.io: https://jitpack.io/com/github/apace100/apoli/624eb4d094/build.log

**Comment by eggohito** [comment]
See https://github.com/apace100/origins-fabric/issues/619#issuecomment-1356816553 for a work around

**Comment by CMD-God** [comment]
Thank you! That helped!

**Comment by elytrafae** [comment]
Thank you! That helped!
