### ISSUE TITLE
Apoli using a not-insignificant % of tick time?

### ISSUE THREAD

**Issue by douglasg14b** [apace100/apoli#158]
[Spark](https://spark.lucko.me/I6Eyl1TiEd?hl=1828,3537,3668,5157,5478,5927,6030,6833,8098,8431,8881,9230,9634,9947,13779,13933,14185,16768,16957,18984,19330)

I'm unsure why/what it's doing, but it seems like `updateItemStackHolder()` is doing a lot every tick?

Is this expected?

**Comment by ChrysanthCow** [comment]
Fixed here for a future update: https://github.com/apace100/apoli/pull/132

**Comment by douglasg14b** [comment]
Thanks!

Can a patch version (n.n.x) be released that includes these changes, are there challenges around that? Regular patch releases are good for both bug isolation, and for server operators/players!

**Comment by eggohito** [comment]
> Thanks!
> 
> Can a patch version (n.n.x) be released that includes these changes, are there challenges around that? Regular patch releases are good for both bug isolation, and for server operators/players!

Currently, no, but we have plans on changing that after the new update is out. At the moment, features and fixes are pushed in a single branch, which is not really ideal for releasing hotfixes
