### ISSUE TITLE
Error on startup to server: "Internal Exception: io.netty.handler.codec.EncoderException: Failed to decode: Not a string, Not a list #290

### ISSUE THREAD

**Issue by Nariod14** [apace100/apoli#176]
I'm not sure if this is the best place to put it, but I do see Apoli listed in the errors so it might be relevant. It's been a while since I last delved into my modpack. So, I decided to rekindle my interest and, perhaps a bit recklessly, updated all my mods before diving back into the game and server. Previously, my modded server ran flawlessly, but now I'm encountering an error when attempting to connect. You can check out both the screenshot and the attached logs for the specifics of the issue. Although the error appears to be related to Origins++ and origins (as in the second screenshot I get another error when I try to only use Origins) I saw apoli here so I thought you might want to have a look.

Any help would be greatly appreciated!

Version: 1.19.2
Forge: 43.2.14

![image](https://github.com/apace100/apoli/assets/21109756/c2e5cf25-5538-448a-8264-4495f35e9a20)
![image](https://github.com/apace100/apoli/assets/21109756/e6d245e8-25b2-4a65-9ae8-f28740d3a7ff)

here are some relevant logs:
https://gist.github.com/Nariod14/41367746843988ef04cdab05184c99ae
[latest.log](https://github.com/apace100/apoli/files/13194520/latest.log)
[server (1).log](https://github.com/apace100/apoli/files/13194523/server.1.log)

**Comment by ChrysanthCow** [comment]
This is an issue for the unofficial Forge port of Origins, not the official Fabric Apoli. This is the repo for the Fabric version.

https://github.com/EdwinMindcraft/origins-architectury is the correct place to report this.

**Comment by Nariod14** [comment]
Thanks for the reply! I will post it there.
