### ISSUE TITLE
[1.20.1 Fabric] Crash with Bumblezone when damaging its Cosmic Crystal Living Entity

### ISSUE THREAD

**Issue by TelepathicGrunt** [apace100/apoli#177]
Apoli (which seems to be a part of Origins), is attaching `shouldApplyArmor` field to my entity by mixin, doesn't populate that field, and then later crashes in `modifyArmorApplicance` method in Apoli's mixin to the point that the world is unplayable and will keep crashing until user disables Origins. 

My mod is Bumblezone and this is the issue report I gotten about this.
https://github.com/TelepathicGrunt/Bumblezone/issues/292

I see no solution on my end as neither the field nor these mixins are owned by me.

https://github.com/apace100/apoli/blob/5895cf5df1ee37e41eab86b0881f3fa3eb235356/src/main/java/io/github/apace100/apoli/mixin/LivingEntityMixin.java#L177C37-L177C53

**Comment by TelepathicGrunt** [comment]
One more thing to note, to make my living entity limit incoming damage to just 1 or 2 and other changes to damaging, I override hurt (damage) method in it. So assuming every Living Entity calls the vanilla hurt method is not a safe assumption to make

https://github.com/TelepathicGrunt/Bumblezone/blob/2b1d7eed6720061e799106af684f7e3fb0c6bacf/common/src/main/java/com/telepathicgrunt/the_bumblezone/entities/living/CosmicCrystalEntity.java#L1381

**Comment by TelepathicGrunt** [comment]
just checking in, was an update released with the fix?

**Comment by eggohito** [comment]
Oh, yes, this has actually been fixed in [Apoli 2.11.0](https://github.com/apace100/apoli/releases/tag/v2.11.0) (specifically, in https://github.com/apace100/apoli/commit/ce5a44b80fcd410c98a303ab93357f3c6668263e), I just forgot to reference the issue

**Comment by TelepathicGrunt** [comment]
Decided to backport the Apoli fix to 1.20.1 by making a small mixin mod to specifically fix this
https://legacy.curseforge.com/minecraft/mc-mods/origins-apoli-armor-mixin-fix
