### ISSUE TITLE
an `Action On Delay (Power Type)` with `Condition Types` would be very helpful.

### ISSUE THREAD

**Issue by Reniel80** [apace100/apoli#181]
This would be perfect for executing actions more efficiently and creating better linked effects.

**Comment by ChrysanthCow** [comment]
Hmm, I'm curious as to what you mean by this.

Like, a recursion type deal? I honestly was thinking of making recurse (loops until a condition is false) and loop (executes an amount of times) action types. Eggolib has a loop action type for example.

I also didn't realise that this was Apoli, not Apugli.

**Comment by Reniel80** [comment]
It would be a linear execution and not a cycle like Action Over Time

**Comment by Reniel80** [comment]
This would be an example (I am using Origins)

```
{
    "type": "origins:multiple",
    "witch_state": {
        "type": "origins:resource",
        "min": 0,
        "max": 3,
        "start_value": 0
    },
    "on_hit": {
        "condition": {
            "type": "origins:entity_type",
            "entity_type": "minecraft:witch"
        },
        "type": "origins:action_on_hit",
        "bientity_action": {
            "type": "origins:actor_action",
            "action": {
                "type": "origins:modify_resource",
                "resource": "*:*_witch_state",
                "modifier": {
                    "operation": "addition",
                    "value": 1
                }
            }
        },
        "cooldown": 1
    },
    "summon": {
        "condition": {
            "type": "origins:resource",
            "resource": "*:*_witch_state",
            "comparison": "==",
            "compare_to": 3
        },
        "type": "origins:action_on_delay",
        "ticks": 1,
        "action": {
            "type": "origins:and",
            "actions": [
                {
                    "type": "origins:execute_command",
                    "command": "/summon skeleton ~ ~ ~-1"
                },
                {
                    "type": "origins:delay",
                    "action": {
                        "type": "origins:execute_command",
                        "command": "/summon zombie~ ~ ~-1"
                    },
                    "ticks": 60
                }
            ]
        }
    }
}
```

After 3 hits... the witch will summon an skeleton in the first tick,  and after 3 seconds, will summon a zombie.
Then you could `change_resource` `*:*_witch_state ` to 0 after another delay.

**Comment by 0vergrown** [comment]
But there's already the Delay meta action and it works and does this exact same thing

**Comment by Reniel80** [comment]
yes but can only be triggered  by an entity action... but.. if i wish to create a combination of effects for example:

simulating your eyes are affected when you go out from a dark place to a sunny place

action_on_delay
condition: brighness > 0.1
action: and
action1: apply_effect ->darkness (duration 40)
ticks: 1
action 2: delay
ticks: 20
action: apply_effect -> blindness (duration 20)

is a transition visual effect from darkness effect to blindness and when it finish, you are back to normal with a better end visual result.

is there any other way to do it?
