### ISSUE TITLE
adding `tag` to the `result` item in `recipe` power, similar to `modify_crafting` power, would be perfect.

### ISSUE THREAD

**Issue by Reniel80** [apace100/apoli#182]
Doing this you can create custom items adding NBT data.

**Comment by eggohito** [comment]
While this would simplify the process of adding custom NBT to the result item of a recipe provided by the `recipe` power type, this would mean that we would have to write a custom serializer for shaped/shapeless recipes. This would also mean that mods that extend the vanilla recipe serializers, like NBT Crafting, will no longer be compatible
