### ISSUE TITLE
Using a wrong dimension in a Modify Player Spawn power creates issues and is not catched

### ISSUE THREAD

**Issue by Creerio** [apace100/apoli#19]
> ### Minecraft and Java Informations

Launcher used : MultiMC V0.6.14-develop-3011

Minecraft version : 1.18.1 w/ Fabric loader 0.12.11

Java version : Openjdk 17.0.1

Mod versions : Origins v1.3.1, Apoli v2.2.2, Fabric API 0.44.0

> ### Summary of the issue

Selecting an origin with a **[Modify Player Spawn](https://origins.readthedocs.io/en/latest/power_types/modify_player_spawn/) power** using a wrong dimension creates issues.

After new world generation, the game stops the world's loading. [Video of world loading with error in MMC logs](https://user-images.githubusercontent.com/44642117/145709521-2fc254ca-a844-48be-87f3-949efb4ff10b.mp4)

It also blocks the respawn button from working properly when dying with no respawn point in an already created world. Same thing with the gamerule **doImmediateRespawn** set to true, except it's a bit weirder. [Video of issue with world and gamerule](https://user-images.githubusercontent.com/44642117/145709531-85b20b95-2212-41b5-b21f-e9a77d737a48.mp4)

Usually, when having a wrong json power file, the mod detects it and blocks it's loading while logging the info, allowing the datapack's creator to understand where the issue is. In this case, it does not. It even attempts to spawn the player there which is not possible, creating theses issues.

For context : The original issue was that I thought an overworld modify player spawn power did no longer work (unlike the 1.16.5 version of origins in which I had no problems), however as pointed out by eehunter (comment under this one), I've made a typo in my power file.

> ### Error message

See [this hatebin](https://hatebin.com/gsasrhhhco)

> ### How to reproduce it

**Step 1** : Create an origin datapack, it must contain at least one origin using a [Modify Player Spawn](https://origins.readthedocs.io/en/latest/power_types/modify_player_spawn/) with a wrong dimension power, for example you can use [this one](https://github.com/apace100/apoli/files/7441456/testorigin.zip)

**Step 2** : Load it in any world, either a new one or an already created one

**Step 3** : If you created a new one, select the origin having the problematic power. If you're using one you've already made before, change your origin to that and kill yourself.

**Step 4** : Check your minecraft logs, you should have the error message.

**Comment by eehunter** [comment]
`snow_mountain_spawn.json` line 5 `"dimension": "minecraft:owerworld",`
Typo in `minecraft:overworld`
The error message is caused by an invalid RegistryKey.
`getSpawn` should log an error message and return null if world is null (I.E. `RegistryKey<World> dimension` does not contain a valid dimension key)

**Comment by Creerio** [comment]
Welp.. I should have verified the dimension name.. It does work as intended with the right one.

Thanks for the help, I will modify the original issue since having an invalid dimension still creates an issue when spawning the player or when reading the json power file (unlike other powers which have their errors catched and logged).
