### ISSUE TITLE
[suggestion] Would be very useful being able to set the `min` and/or `max` value of a `resource` via mod config.

### ISSUE THREAD

**Issue by Reniel80** [apace100/apoli#201]
That way players will be able to customize some power parameters.

**Comment by eggohito** [comment]
I don't think this would provide any more flexibility with configuring a resource's min/max values, considering that the config is global. This would also set the expectation for fields of other power/action/condition types, which could clutter the config file greatly considering how many are added just with Apoli alone

**Comment by ChrysanthCow** [comment]
Another thing I'll add is that certain powers are very intentionally designed to have specific values in conditions, and they check those values.

Changing this from just a config could break many things with certain Origins with these sorts of solutions.
