### ISSUE TITLE
Internal Exception

### ISSUE THREAD

**Issue by euquinox** [apace100/apoli#202]
hi! I keep getting this error whenever I am trying to generate a new world or join an existing one

Internal Exception: java.lang.IllegalArgumentException: Registry ResourceKey[minecraft:root/apoli:configured_power] was missing

[latest.log](https://github.com/apace100/apoli/files/13930232/latest.log)

**Comment by eggohito** [comment]
You're using the unofficial Forge port. This repository is for the official version, which is for Fabric. You can report issues regarding the unofficial Forge port in https://github.com/EdwinMindcraft/origins-architectury/issues

**Comment by euquinox** [comment]
thank you! my apologies
