### ISSUE TITLE
[1.20.1] Failed to connect to the server (my local world)

### ISSUE THREAD

**Issue by eugegene** [apace100/apoli#218]
Internal Exception: Java.lang.IllegalArgumentException: Register
Can't join to the save, and after exception world dissapears from serverlist, but not from the files.
Can't create another worlds either.
I have played since January of this year, and my world now about 10gb's.
I'm really afraid lose it.
Class human btw.
Logs: https://mclo.gs/2x929VU

**Comment by eugegene** [comment]
Logs: https://mclo.gs/2x929VU

**Comment by eugegene** [comment]
I updated the mod to the latest version and the world started BUT I lost all the items I had on (rings, amulets, etc.) and my backpack with all my stuff disappeared. Skills from skills tree mod dissapeared too.
I saved the world after the bug, but not after the mod update.

**Comment by eugegene** [comment]
I turned off the mod in the launcher and went back to save - the world started, everything is in place.
Since I had a human class, I didn't lose much. The problem will be solved

**Comment by eggohito** [comment]
By the way, this isn't really the appropriate place to report issues regarding the Forge port since this is for Fabric. You should be reporting this issue at https://github.com/EdwinMindcraft/origins-architectury/issues

**Comment by eugegene** [comment]
My bad, i get link to this place :(
