### ISSUE TITLE
Enchantment Power Types for Players/Mobs

### ISSUE THREAD

**Issue by 256smash** [apace100/apoli#220]
Enchantments could be applied to any mob such as Frost Walker, Thorns, and Soul Speed without using armor. 

Example code:
`
"type":"apoli:enchantment",
"enchants": [
"minecraft:frost_walker",
"minecraft:multishot"
]
`

I might also suggest that conditions can be used for abilities since they are also necessary.

**Comment by eggohito** [comment]
This is actually already possible with the [`modify_enchantment_level` power type](https://origins.readthedocs.io/en/latest/types/power_types/modify_enchantment_level), which was introduced in [Origins 1.11.0](https://github.com/apace100/origins-fabric/releases/tag/v1.11.0) ([Apoli v2.10.0](https://github.com/apace100/apoli/releases/tag/v2.10.0))

**Comment by 256smash** [comment]
Thanks for reminding me
