### ISSUE TITLE
Incompatibility with Mods of Mythology on 1.20.1

### ISSUE THREAD

**Issue by Rattle189** [apace100/apoli#249]
I run a small 1.20.1 Fabric server that has a self-assembled modpack that tries to replicate an RPG experience. One of those mods is [Mobs of Mythology](https://github.com/kyber-6/mobs-of-mythology-mod) running on version 2.0.0 and it seems like the apoli library has some sort of incompatibility causing the server to crash when mobs from the mod are killed.

What happened exactly is a mob called the Kobold stole an item from a player, it was the Royal Longbow from Archers (RPG Series) that was enchanted with Infinity & Unbreaking 3. The player killed the mob and the server shortly crashed.

It doesn't seem like the crashing is consistent but it still happens randomly, a server crash log is provided below:
[crash-2024-08-02_21.23.11-server.txt](https://github.com/user-attachments/files/16478436/crash-2024-08-02_21.23.11-server.txt)

**Comment by eggohito** [comment]
Marking as duplicate since this is already being tracked in https://github.com/apace100/apoli/issues/178
