### ISSUE TITLE
Mixin incompatibility with Destroy

### ISSUE THREAD

**Issue by tlitookilakin** [apace100/apoli#255]
Installing Destroy alongside Apoli causes Apoli's mixin to break, causing a startup crash.

[game log](https://mclo.gs/MjJkGsU)

Mod List:
- Destroy 0.1.0-Snapshot-10
- Create 0.5.1h
- Origins 1.10.0.9
- Petrolpark lib 1.0.6
- Caelus 3.2.0
- neoforged 47.1.100

Also reported on the Destroy repository [here](petrolpark/Destroy#511).

**Comment by eggohito** [comment]
This repository is for the official version of Apoli, which is for Fabric. If you're having issues with the Forge port, you should report said issues to https://github.com/EdwinMindcraft/origins-architectury/issues

**Comment by tlitookilakin** [comment]
Ah, sorry about that! Thanks for the redirect.
