### ISSUE TITLE
Incompatible with Emotecraft

### ISSUE THREAD

**Issue by KosmX** [apace100/apoli#31]
In LivingEntityRenderer, both mods are using the same redirect opportunity

apoli redirect
https://github.com/apace100/apoli/blob/434a118654e28888a1611324d0deba0f77656293/src/main/java/io/github/apace100/apoli/mixin/LivingEntityRendererMixin.java#L59

emotes redirect
https://github.com/KosmX/emotes/blob/0487d21c85d3e2b6503e8944a52d7f1b6cbf7bb2/17/fabric/src/main/java/io/github/kosmx/emotes/fabric/mixin/LivingEntityRenderRedirect.java#L26

**Comment by KosmX** [comment]
Issue in `emotes` repo
https://github.com/KosmX/emotes/issues/181

**Comment by KosmX** [comment]
I could target `Iterator.next`.
And solve the issue for now.

**Comment by KosmX** [comment]
In theory, I did a workaround by targeting `Iterator`  
But there should be a better way for this.

**Comment by ChrysanthCow** [comment]
This has been long fixed, and the redirect doesn't even exist anymore thanks to Mixin Extras!

Could we please close this issue?
