### ISSUE TITLE
Truffle decomposition not effecting non-splash potions

### ISSUE THREAD

**Issue by Set2Minecraft** [apace100/apoli#40]
When drinking a potion as a truffle you still gain effects from potion, im not sure if this is a bug or not but when reading the effects list, I assumed that the decomposition attribute would also affect drinking potions.

**Comment by MerchantPug** [comment]
This would be an [Extra Origins](https://github.com/MoriyaShiine/extra-origins) issue, not an Apoli issue.

But as to answer your question, this is intended behavior.
