### ISSUE TITLE
Failure to find structure causes origin to be unable to respawn

### ISSUE THREAD

**Issue by Linguardium** [apace100/apoli#55]
https://github.com/apace100/apoli/blob/750d0cb44d3e9bad8ce03787e7606049ba544400/src/main/java/io/github/apace100/apoli/power/ModifyPlayerSpawnPower.java#L78

Failure to find structure causes origin to be unable to respawn. Suggest falling back to default spawn if structure is not found.

**Comment by eggohito** [comment]
This should now be fixed in [Apoli v2.9.0](https://github.com/apace100/apoli/releases/tag/v2.9.0)
