### ISSUE TITLE
Item condition splash_potion does not seem to be working

### ISSUE THREAD

**Issue by CoutteauSam** [apace100/apoli#79]
Using a splash potion doesn't seem to activate the following power

```json
{
  "type": "origins:action_on_item_use",
  "item_condition": {
    "type": "origins:ingredient",
    "ingredient": {
      "item": "minecraft:splash_potion"
    }
  },
  "entity_action": {
    "type": "origins:give",
    "stack": {
      "item": "minecraft:splash_potion",
      "amount": 1
    }
  }
}
```
`minecraft=1.19.3`
`origins_version=v1.8.1`

**Comment by eggohito** [comment]
This should now work in [Apoli 2.8.0](https://github.com/apace100/apoli/releases/tag/v2.8.0), which is used by [Origins 1.9.0](https://github.com/apace100/origins-fabric/releases/tag/v1.9.0)
