### ISSUE TITLE
Major TPS spiking

### ISSUE THREAD

**Issue by archynoid** [apace100/apoli#85]
I've been going around trying to get to the bottom of the TPS lag that is occuring on a server I am running. TPS spikes hard as more and more people join and it doesn't recover unless people leave. After going around a few different places I was able to find my way here. I have a few screenshots of what is doing most of the load, do you have any idea what is causing this?

[1](https://i.imgur.com/FRbx4RU.png)
[2](https://i.imgur.com/FRbx4RU.png)
[3](https://i.imgur.com/MSy69rV.png)
[4](https://i.imgur.com/WWhXcF3.png)

**Comment by archynoid** [comment]
Really trying to get to the bottom of what is spamming these executes, the core of it seems to be from apace100.

**Comment by itsdinkd** [comment]
remove any custom origin packs you added

**Comment by apace100** [comment]
Hi @archynoid, sorry for the late reply.
Judging by your third screenshot, it looks like you're not using this mod, but instead the Forge port by EdwinMindcraft. I suggest reporting performance issues there, as I'm unsure how much the actual implementations differ.
